### ISSUE TITLE
Make the "Set" button in device actually push the configuration

### ISSUE THREAD

**Issue by soravux** [lvsn/CameraNetwork#3]
As of now, the configuration is pushed the next time a single capture is taken.

How to reproduce a bug of this nature: Click on Set in device panel, switch to network panel and take a picture. The configuration won't be the new one but the old one.

**Comment by MathGaron** [comment]
This bug comes from the fact that we use the parameter server for the current configuration. We could simply call a new service from controller. I will look forward if we can remove these configurations from parameter server and simply make a get_config instead to get the data from the driver directly

**Comment by MathGaron** [comment]
The javascript code use the parameter server to refresh data on screen, using get_config on devices would be time consuming and bad for the system : it would have to ask every camera at every refresh, so I will simply add the service

**Comment by soravux** [comment]
Done in commits 00ce2a20fc2dfbd7360d347f03fbde13c45297bd (client) and 5f537d5c6dfafcca1f09a3f7c550e0604269c491 / 640c2b66b5d8047cafc7cf60d2f4f9f8cf6807e7 (server)
